apiVersion: v1
kind: Service
metadata:
    annotations:
        consul.hashicorp.com/service-name: minitiktok-auth-grpc
        consul.hashicorp.com/service-port: grpc
        consul.hashicorp.com/service-sync: 'true'
        consul.hashicorp.com/service-tags: 'grpc,minitiktok,14514'
    labels:
        app: minitiktok-auth-grpc
    name: minitiktok-auth-grpc
    namespace: minitiktok-auth-grpc
spec:
    ports:
        -   name: grpc
            port: 14514
            protocol: TCP
            targetPort: 14514
    selector:
        name: minitiktok-auth-grpc
        branch: dev
    type: ClusterIP
